### ISSUE TITLE
Subpixel problem still happening in some cases.

### ISSUE THREAD

**Issue by Serabe** [src-d/landing#126]
![2017-08-16 at 10 47](https://user-images.githubusercontent.com/36221/29355213-6ddff7fc-8270-11e7-8b29-c4e7855ea04f.png)

**Comment by marnovo** [comment]
@ricardobaeta can you confirm this ever happens with you?

**Comment by ricardobaeta** [comment]
@marnovo I can't replicate this issue. Desktop & Mobile.

**Comment by Serabe** [comment]
![2017-10-24 at 11 54](https://user-images.githubusercontent.com/36221/31936545-291663b8-b8b2-11e7-9744-33b2b2409ab7.png)

I still can.

**Comment by ricardobaeta** [comment]
@Serabe What's the url please? Mobile & Desktp?

**Comment by Serabe** [comment]
[sourced.tech](sourced.tech) See the responsive settings in the image above. In an iPhone 6s Plus can be reproduce going to the page and zooming a bit.

**Comment by ricardobaeta** [comment]
No need to confirm, thanks a lot @Serabe !

@dpordomingo Do you need anything on my side for this?

**Comment by dpordomingo** [comment]
I finally could reproduce it following Sergio screenshot.
Trying to fix it

**Comment by dpordomingo** [comment]
Hi @Serabe could you confirm in a real device that it's fixed in staging?
https://landing-staging.srcd.run
It should be fixed (I was able to fix it in chrome inspector...)


Many many thanks!

**Comment by Serabe** [comment]
![1e179ebc-033a-454a-a127-899ec0e18f85](https://user-images.githubusercontent.com/36221/32026407-90894b72-b9e4-11e7-8749-2e31e1ddb470.jpg)

Still happening, though thinner.
